// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module main_flow_v_tpg_0_2_tpgPatternCrossHatch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        y,
        x,
        width,
        height,
        color,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] y;
input  [15:0] x;
input  [15:0] width;
input  [15:0] height;
input  [7:0] color;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
reg   [9:0] yCount_V_2;
reg   [0:0] vHatch;
reg   [9:0] xCount_V_2;
wire   [1:0] whiYuv_address0;
reg    whiYuv_ce0;
wire   [7:0] whiYuv_q0;
wire   [1:0] blkYuv_1_address0;
reg    blkYuv_1_ce0;
wire   [7:0] blkYuv_1_q0;
wire   [0:0] icmp_ln1404_fu_198_p2;
reg   [0:0] icmp_ln1404_reg_526;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln1404_fu_204_p1;
reg   [0:0] trunc_ln1404_reg_530;
wire   [0:0] icmp_ln1404_1_fu_212_p2;
reg   [0:0] icmp_ln1404_1_reg_535;
wire   [0:0] and_ln1404_fu_230_p2;
reg   [0:0] and_ln1404_reg_540;
wire   [9:0] tmp_fu_236_p4;
wire   [0:0] cmp80_fu_258_p2;
wire   [0:0] cmp82_fu_264_p2;
wire   [0:0] icmp_ln1428_fu_270_p2;
reg   [0:0] icmp_ln1428_reg_564;
wire   [9:0] grp_reg_ap_uint_10_s_fu_174_d;
wire   [9:0] grp_reg_ap_uint_10_s_fu_174_ap_return;
reg    grp_reg_ap_uint_10_s_fu_174_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call10;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call10;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call10;
wire    ap_block_pp0_stage0_11001_ignoreCallOp14;
wire   [0:0] ap_phi_reg_pp0_iter0_hHatch_reg_122;
reg   [0:0] ap_phi_reg_pp0_iter1_hHatch_reg_122;
reg   [0:0] ap_phi_reg_pp0_iter2_hHatch_reg_122;
wire   [0:0] icmp_ln1073_fu_356_p2;
wire   [0:0] icmp_ln1065_1_fu_362_p2;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1459_fu_417_p1;
wire   [9:0] add_ln886_fu_316_p2;
wire   [0:0] and_ln1409_fu_311_p2;
wire   [9:0] sub_ln887_fu_368_p2;
wire   [9:0] add_ln886_3_fu_386_p2;
wire   [13:0] trunc_ln1396_fu_148_p1;
wire   [13:0] add_ln1396_fu_152_p2;
wire   [9:0] trunc_ln_fu_158_p4;
wire   [13:0] trunc_ln1398_fu_184_p1;
wire   [16:0] zext_ln1398_fu_180_p1;
wire   [16:0] zext_ln1404_fu_194_p1;
wire   [16:0] add_ln1404_fu_218_p2;
wire   [0:0] icmp_ln1404_2_fu_224_p2;
wire   [13:0] add_ln1398_fu_188_p2;
wire   [16:0] zext_ln1396_fu_144_p1;
wire   [16:0] zext_ln1404_1_fu_208_p1;
wire   [16:0] sub40_fu_252_p2;
wire   [10:0] zext_ln1542_fu_288_p1;
wire   [10:0] zext_ln1065_fu_301_p1;
wire   [10:0] ret_V_fu_291_p2;
wire   [0:0] icmp_ln1065_fu_305_p2;
wire   [0:0] or_ln1459_fu_405_p2;
wire   [1:0] select_ln1459_1_fu_398_p3;
wire   [1:0] select_ln1459_fu_409_p3;
wire   [0:0] or_ln1449_fu_441_p2;
wire   [0:0] xor_ln1449_fu_452_p2;
wire   [0:0] sel_tmp6_fu_458_p2;
wire   [0:0] sel_tmp_fu_447_p2;
wire   [0:0] or_cond_fu_471_p2;
wire   [7:0] newSel_fu_463_p3;
wire   [7:0] newSel9_fu_476_p3;
wire   [7:0] conv2_i_i15_fu_427_p3;
wire   [7:0] conv2_i_i_fu_434_p3;
wire   [7:0] select_ln1472_fu_500_p3;
wire   [7:0] pix_val_V_fu_484_p3;
wire   [7:0] pix_val_V_8_fu_492_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_467;
reg    ap_condition_472;
reg    ap_condition_476;
reg    ap_condition_480;
reg    ap_condition_81;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 yCount_V_2 = 10'd0;
#0 vHatch = 1'd0;
#0 xCount_V_2 = 10'd0;
end

main_flow_v_tpg_0_2_tpgPatternCrossHatch_whiYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_address0),
    .ce0(whiYuv_ce0),
    .q0(whiYuv_q0)
);

main_flow_v_tpg_0_2_tpgPatternCrossHatch_blkYuv_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
blkYuv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blkYuv_1_address0),
    .ce0(blkYuv_1_ce0),
    .q0(blkYuv_1_q0)
);

main_flow_v_tpg_0_2_reg_ap_uint_10_s grp_reg_ap_uint_10_s_fu_174(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(grp_reg_ap_uint_10_s_fu_174_d),
    .ap_return(grp_reg_ap_uint_10_s_fu_174_ap_return),
    .ap_ce(grp_reg_ap_uint_10_s_fu_174_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln1404_1_fu_212_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1428_fu_270_p2 == 1'd1)) | ((icmp_ln1404_1_fu_212_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_reg_pp0_iter1_hHatch_reg_122 <= 1'd1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_hHatch_reg_122 <= ap_phi_reg_pp0_iter0_hHatch_reg_122;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1404_1_reg_535 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1065_1_fu_362_p2 == 1'd1) & (icmp_ln1073_fu_356_p2 == 1'd0) & (icmp_ln1428_reg_564 == 1'd0))) begin
        ap_phi_reg_pp0_iter2_hHatch_reg_122 <= 1'd1;
    end else if ((((icmp_ln1404_1_reg_535 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1065_1_fu_362_p2 == 1'd0) & (icmp_ln1073_fu_356_p2 == 1'd0) & (icmp_ln1428_reg_564 == 1'd0)) | ((icmp_ln1404_1_reg_535 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1073_fu_356_p2 == 1'd1) & (icmp_ln1428_reg_564 == 1'd0)))) begin
        ap_phi_reg_pp0_iter2_hHatch_reg_122 <= 1'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_hHatch_reg_122 <= ap_phi_reg_pp0_iter1_hHatch_reg_122;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((1'd1 == and_ln1404_reg_540) & (icmp_ln1404_reg_526 == 1'd0)) | ((icmp_ln1404_1_reg_535 == 1'd1) & (icmp_ln1404_reg_526 == 1'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((1'd1 == and_ln1409_fu_311_p2) & (icmp_ln1404_reg_526 == 1'd0) & (1'd0 == and_ln1404_reg_540)) | ((1'd1 == and_ln1409_fu_311_p2) & (icmp_ln1404_1_reg_535 == 1'd0) & (icmp_ln1404_reg_526 == 1'd1)))))) begin
        vHatch <= 1'd1;
    end else if (((icmp_ln1404_1_reg_535 == 1'd1) & (icmp_ln1404_reg_526 == 1'd0) & (1'd0 == and_ln1404_reg_540) & (1'd0 == and_ln1409_fu_311_p2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vHatch <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_81)) begin
        if (((icmp_ln1404_1_fu_212_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            xCount_V_2 <= 10'd0;
        end else if ((1'b1 == ap_condition_480)) begin
            xCount_V_2 <= 10'd0;
        end else if ((1'b1 == ap_condition_476)) begin
            xCount_V_2 <= add_ln886_3_fu_386_p2;
        end else if ((1'b1 == ap_condition_472)) begin
            xCount_V_2 <= 10'd0;
        end else if ((1'b1 == ap_condition_467)) begin
            xCount_V_2 <= sub_ln887_fu_368_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((1'd1 == and_ln1404_fu_230_p2) & (icmp_ln1404_fu_198_p2 == 1'd0)) | ((icmp_ln1404_1_fu_212_p2 == 1'd1) & (icmp_ln1404_fu_198_p2 == 1'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((1'd1 == and_ln1409_fu_311_p2) & (icmp_ln1404_reg_526 == 1'd0) & (1'd0 == and_ln1404_reg_540)) | ((1'd1 == and_ln1409_fu_311_p2) & (icmp_ln1404_1_reg_535 == 1'd0) & (icmp_ln1404_reg_526 == 1'd1)))))) begin
        yCount_V_2 <= 10'd0;
    end else if (((icmp_ln1404_1_reg_535 == 1'd1) & (icmp_ln1404_reg_526 == 1'd0) & (1'd0 == and_ln1404_reg_540) & (1'd0 == and_ln1409_fu_311_p2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        yCount_V_2 <= add_ln886_fu_316_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1404_fu_198_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln1404_reg_540 <= and_ln1404_fu_230_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1404_1_reg_535 <= icmp_ln1404_1_fu_212_p2;
        icmp_ln1404_reg_526 <= icmp_ln1404_fu_198_p2;
        trunc_ln1404_reg_530 <= trunc_ln1404_fu_204_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1404_1_fu_212_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1428_reg_564 <= icmp_ln1428_fu_270_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        blkYuv_1_ce0 = 1'b1;
    end else begin
        blkYuv_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp14) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_reg_ap_uint_10_s_fu_174_ap_ce = 1'b1;
    end else begin
        grp_reg_ap_uint_10_s_fu_174_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        whiYuv_ce0 = 1'b1;
    end else begin
        whiYuv_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1396_fu_152_p2 = (trunc_ln1396_fu_148_p1 + 14'd15);

assign add_ln1398_fu_188_p2 = (trunc_ln1398_fu_184_p1 + 14'd15);

assign add_ln1404_fu_218_p2 = ($signed(zext_ln1398_fu_180_p1) + $signed(17'd131071));

assign add_ln886_3_fu_386_p2 = (xCount_V_2 + 10'd1);

assign add_ln886_fu_316_p2 = (yCount_V_2 + 10'd1);

assign and_ln1404_fu_230_p2 = (icmp_ln1404_2_fu_224_p2 & icmp_ln1404_1_fu_212_p2);

assign and_ln1409_fu_311_p2 = (icmp_ln1404_1_reg_535 & icmp_ln1065_fu_305_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call10 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_467 = ((icmp_ln1404_1_reg_535 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1065_1_fu_362_p2 == 1'd0) & (icmp_ln1073_fu_356_p2 == 1'd0) & (icmp_ln1428_reg_564 == 1'd0));
end

always @ (*) begin
    ap_condition_472 = ((icmp_ln1404_1_reg_535 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1065_1_fu_362_p2 == 1'd1) & (icmp_ln1073_fu_356_p2 == 1'd0) & (icmp_ln1428_reg_564 == 1'd0));
end

always @ (*) begin
    ap_condition_476 = ((icmp_ln1404_1_reg_535 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1073_fu_356_p2 == 1'd1) & (icmp_ln1428_reg_564 == 1'd0));
end

always @ (*) begin
    ap_condition_480 = ((icmp_ln1404_1_fu_212_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln1428_fu_270_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_81 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_hHatch_reg_122 = 'bx;

assign ap_return_0 = select_ln1472_fu_500_p3;

assign ap_return_1 = pix_val_V_fu_484_p3;

assign ap_return_2 = pix_val_V_8_fu_492_p3;

assign blkYuv_1_address0 = zext_ln1459_fu_417_p1;

assign cmp80_fu_258_p2 = ((color == 8'd0) ? 1'b1 : 1'b0);

assign cmp82_fu_264_p2 = ((color == 8'd1) ? 1'b1 : 1'b0);

assign conv2_i_i15_fu_427_p3 = ((cmp80_fu_258_p2[0:0] == 1'b1) ? 8'd255 : 8'd128);

assign conv2_i_i_fu_434_p3 = ((cmp80_fu_258_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign grp_reg_ap_uint_10_s_fu_174_d = ($signed(trunc_ln_fu_158_p4) + $signed(10'd1023));

assign icmp_ln1065_1_fu_362_p2 = ((xCount_V_2 == grp_reg_ap_uint_10_s_fu_174_ap_return) ? 1'b1 : 1'b0);

assign icmp_ln1065_fu_305_p2 = ((zext_ln1065_fu_301_p1 == ret_V_fu_291_p2) ? 1'b1 : 1'b0);

assign icmp_ln1073_fu_356_p2 = ((xCount_V_2 < grp_reg_ap_uint_10_s_fu_174_ap_return) ? 1'b1 : 1'b0);

assign icmp_ln1404_1_fu_212_p2 = ((x == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1404_2_fu_224_p2 = ((zext_ln1404_fu_194_p1 == add_ln1404_fu_218_p2) ? 1'b1 : 1'b0);

assign icmp_ln1404_fu_198_p2 = ((y == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1428_fu_270_p2 = ((zext_ln1404_1_fu_208_p1 == sub40_fu_252_p2) ? 1'b1 : 1'b0);

assign newSel9_fu_476_p3 = ((sel_tmp_fu_447_p2[0:0] == 1'b1) ? 8'd255 : blkYuv_1_q0);

assign newSel_fu_463_p3 = ((sel_tmp6_fu_458_p2[0:0] == 1'b1) ? 8'd0 : whiYuv_q0);

assign or_cond_fu_471_p2 = (or_ln1449_fu_441_p2 ^ cmp80_fu_258_p2);

assign or_ln1449_fu_441_p2 = (vHatch | ap_phi_reg_pp0_iter2_hHatch_reg_122);

assign or_ln1459_fu_405_p2 = (trunc_ln1404_reg_530 | cmp82_fu_264_p2);

assign pix_val_V_8_fu_492_p3 = ((or_ln1449_fu_441_p2[0:0] == 1'b1) ? conv2_i_i15_fu_427_p3 : conv2_i_i_fu_434_p3);

assign pix_val_V_fu_484_p3 = ((or_cond_fu_471_p2[0:0] == 1'b1) ? newSel_fu_463_p3 : newSel9_fu_476_p3);

assign ret_V_fu_291_p2 = ($signed(zext_ln1542_fu_288_p1) + $signed(11'd2047));

assign sel_tmp6_fu_458_p2 = (xor_ln1449_fu_452_p2 & cmp80_fu_258_p2);

assign sel_tmp_fu_447_p2 = (or_ln1449_fu_441_p2 & cmp80_fu_258_p2);

assign select_ln1459_1_fu_398_p3 = ((cmp82_fu_264_p2[0:0] == 1'b1) ? 2'd1 : 2'd2);

assign select_ln1459_fu_409_p3 = ((or_ln1459_fu_405_p2[0:0] == 1'b1) ? select_ln1459_1_fu_398_p3 : 2'd1);

assign select_ln1472_fu_500_p3 = ((or_ln1449_fu_441_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign sub40_fu_252_p2 = ($signed(zext_ln1396_fu_144_p1) + $signed(17'd131071));

assign sub_ln887_fu_368_p2 = (xCount_V_2 - grp_reg_ap_uint_10_s_fu_174_ap_return);

assign tmp_fu_236_p4 = {{add_ln1398_fu_188_p2[13:4]}};

assign trunc_ln1396_fu_148_p1 = width[13:0];

assign trunc_ln1398_fu_184_p1 = height[13:0];

assign trunc_ln1404_fu_204_p1 = x[0:0];

assign trunc_ln_fu_158_p4 = {{add_ln1396_fu_152_p2[13:4]}};

assign whiYuv_address0 = zext_ln1459_fu_417_p1;

assign xor_ln1449_fu_452_p2 = (or_ln1449_fu_441_p2 ^ 1'd1);

assign zext_ln1065_fu_301_p1 = yCount_V_2;

assign zext_ln1396_fu_144_p1 = width;

assign zext_ln1398_fu_180_p1 = height;

assign zext_ln1404_1_fu_208_p1 = x;

assign zext_ln1404_fu_194_p1 = y;

assign zext_ln1459_fu_417_p1 = select_ln1459_fu_409_p3;

assign zext_ln1542_fu_288_p1 = tmp_fu_236_p4;

endmodule //main_flow_v_tpg_0_2_tpgPatternCrossHatch
