// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module main_flow_v_tpg_0_2_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        height,
        width,
        bckgndId,
        ZplateHorContStart,
        ZplateHorContDelta,
        ZplateVerContStart,
        ZplateVerContDelta,
        dpDynamicRange,
        dpYUVCoef,
        motionSpeed,
        colorFormat,
        bckgndYUV_din,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        bckgndYUV_full_n,
        bckgndYUV_write,
        s
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] height;
input  [15:0] width;
input  [7:0] bckgndId;
input  [15:0] ZplateHorContStart;
input  [15:0] ZplateHorContDelta;
input  [15:0] ZplateVerContStart;
input  [15:0] ZplateVerContDelta;
input  [7:0] dpDynamicRange;
input  [7:0] dpYUVCoef;
input  [7:0] motionSpeed;
input  [7:0] colorFormat;
output  [23:0] bckgndYUV_din;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg start_write;
reg bckgndYUV_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] rampStart;
reg   [15:0] rampVal_1;
reg   [7:0] rampVal;
reg   [7:0] hBarSel_2;
reg   [10:0] xBar_V;
reg   [15:0] zonePlateVAddr;
reg   [15:0] zonePlateVDelta;
reg   [15:0] hdata;
reg   [15:0] rampVal_2;
wire   [13:0] trunc_ln506_fu_585_p1;
wire   [0:0] cmp2_i322_fu_589_p2;
wire   [0:0] cmp6_i_fu_603_p2;
reg   [7:0] rampStart_load_reg_1087;
wire   [7:0] select_ln260_fu_687_p3;
reg   [7:0] select_ln260_reg_1093;
wire   [15:0] shl_ln_fu_695_p3;
reg   [15:0] shl_ln_reg_1098;
reg   [15:0] y_3_reg_1108;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp12_i_fu_775_p2;
reg   [0:0] cmp12_i_reg_1116;
wire   [0:0] icmp_ln518_fu_764_p2;
wire   [7:0] add_ln1488_fu_792_p2;
reg   [7:0] add_ln1488_reg_1121;
wire   [0:0] or_ln1592_fu_810_p2;
reg   [0:0] or_ln1592_reg_1126;
wire   [0:0] or_ln1592_1_fu_823_p2;
reg   [0:0] or_ln1592_1_reg_1131;
wire   [0:0] or_ln1592_2_fu_830_p2;
reg   [0:0] or_ln1592_2_reg_1136;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_ready;
wire   [23:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_bckgndYUV_write;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_conv2_i_i_i;
wire   [1:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_select_ln1162_5;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_cmp57_i;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_barWidth_cast;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_barWidth;
wire   [13:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_trunc_ln;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_cmp85_i;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_4_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_4_loc_1_out_o_ap_vld;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_lhs_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_lhs_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_2_0_0_0491_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_2_0_0_0491_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_1_0_0_0489_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_1_0_0_0489_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_0_0_0_0487_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_0_0_0_0487_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_2_ap_vld;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_xBar_V;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_xBar_V_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_366_p4;
reg   [0:0] rampVal_3_flag_0_reg_362;
reg    ap_block_state1;
wire    ap_CS_fsm_state4;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_378_p4;
reg   [0:0] hdata_flag_0_reg_374;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_390_p4;
reg   [0:0] rampVal_2_flag_0_reg_386;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [15:0] rampVal_3_new_0_fu_280;
reg   [15:0] rampVal_3_loc_0_fu_276;
reg   [15:0] rampVal_loc_0_fu_272;
reg   [7:0] hBarSel_4_loc_0_fu_268;
reg   [10:0] xBar_V_loc_0_fu_264;
reg   [15:0] zonePlateVAddr_loc_0_fu_260;
reg   [15:0] zonePlateVDelta_loc_0_fu_256;
reg   [15:0] hdata_new_0_fu_252;
reg   [15:0] hdata_loc_0_fu_248;
reg   [15:0] rampVal_2_new_0_fu_244;
reg   [15:0] rampVal_2_loc_0_fu_240;
reg   [7:0] p_0_2_0_0_0492_lcssa501_fu_236;
reg   [7:0] p_0_1_0_0_0490_lcssa498_fu_232;
reg   [7:0] p_0_0_0_0_0488_lcssa495_fu_228;
wire   [7:0] add_ln705_fu_842_p2;
reg   [15:0] y_fu_224;
wire   [15:0] y_4_fu_769_p2;
wire   [15:0] zext_ln1212_fu_659_p1;
wire   [13:0] add_i_fu_609_p2;
wire   [6:0] tmp_fu_631_p4;
wire   [7:0] trunc_ln518_fu_760_p1;
wire   [1:0] Sel_fu_782_p4;
wire   [0:0] icmp_ln1592_fu_798_p2;
wire   [0:0] icmp_ln1592_1_fu_804_p2;
wire   [0:0] icmp_ln1592_2_fu_817_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 rampStart = 8'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 8'd0;
#0 hBarSel_2 = 8'd0;
#0 xBar_V = 11'd0;
#0 zonePlateVAddr = 16'd0;
#0 zonePlateVDelta = 16'd0;
#0 hdata = 16'd0;
#0 rampVal_2 = 16'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_start_reg = 1'b0;
end

main_flow_v_tpg_0_2_tpgBackground_Pipeline_VITIS_LOOP_520_2 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_ready),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_bckgndYUV_din),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_bckgndYUV_write),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_362),
    .hdata_flag_0(hdata_flag_0_reg_374),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_386),
    .loopWidth(width),
    .conv2_i_i_i(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_conv2_i_i_i),
    .select_ln260(select_ln260_reg_1093),
    .rampStart_1(rampStart_load_reg_1087),
    .Zplate_Hor_Control_Start(ZplateHorContStart),
    .bckgndId_load(bckgndId),
    .cmp2_i322(cmp2_i322_fu_589_p2),
    .zext_ln1032(rampStart_load_reg_1087),
    .y(y_3_reg_1108),
    .cmp6_i(cmp6_i_fu_603_p2),
    .select_ln1162_5(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_select_ln1162_5),
    .cmp57_i(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_cmp57_i),
    .barWidth_cast(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_barWidth_cast),
    .barWidth(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_barWidth),
    .shl_ln(shl_ln_reg_1098),
    .Zplate_Ver_Control_Start(ZplateVerContStart),
    .Zplate_Hor_Control_Delta(ZplateHorContDelta),
    .cmp12_i(cmp12_i_reg_1116),
    .Zplate_Ver_Control_Delta(ZplateVerContDelta),
    .trunc_ln7(trunc_ln506_fu_585_p1),
    .trunc_ln(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_trunc_ln),
    .colorFormatLocal(colorFormat),
    .loopHeight(height),
    .add_ln1488(add_ln1488_reg_1121),
    .cmp85_i(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_cmp85_i),
    .or_ln1592(or_ln1592_reg_1126),
    .or_ln1592_1(or_ln1592_1_reg_1131),
    .or_ln1592_2(or_ln1592_2_reg_1136),
    .dpDynamicRange_load(dpDynamicRange),
    .dpYUVCoef_load(dpYUVCoef),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_276),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_272),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_loc_1_out_o_ap_vld),
    .hBarSel_4_loc_1_out_i(hBarSel_4_loc_0_fu_268),
    .hBarSel_4_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_4_loc_1_out_o),
    .hBarSel_4_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_4_loc_1_out_o_ap_vld),
    .lhs_out_i(xBar_V_loc_0_fu_264),
    .lhs_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_lhs_out_o),
    .lhs_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_lhs_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_260),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr_loc_1_out_o_ap_vld),
    .zonePlateVDelta_loc_1_out_i(zonePlateVDelta_loc_0_fu_256),
    .zonePlateVDelta_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta_loc_1_out_o),
    .zonePlateVDelta_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta_loc_1_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_248),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_loc_1_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_240),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_loc_1_out_o_ap_vld),
    .p_0_2_0_0_0491_out_i(p_0_2_0_0_0492_lcssa501_fu_236),
    .p_0_2_0_0_0491_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_2_0_0_0491_out_o),
    .p_0_2_0_0_0491_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_2_0_0_0491_out_o_ap_vld),
    .p_0_1_0_0_0489_out_i(p_0_1_0_0_0490_lcssa498_fu_232),
    .p_0_1_0_0_0489_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_1_0_0_0489_out_o),
    .p_0_1_0_0_0489_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_1_0_0_0489_out_o_ap_vld),
    .p_0_0_0_0_0487_out_i(p_0_0_0_0_0488_lcssa495_fu_228),
    .p_0_0_0_0_0487_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_0_0_0_0487_out_o),
    .p_0_0_0_0_0487_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_0_0_0_0487_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_ap_vld),
    .hBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_2),
    .hBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_2_ap_vld),
    .xBar_V(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_xBar_V),
    .xBar_V_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_xBar_V_ap_vld),
    .s(s),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr_ap_vld),
    .zonePlateVDelta(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta),
    .zonePlateVDelta_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd0))) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_4_loc_0_fu_268 <= hBarSel_2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_4_loc_1_out_o_ap_vld == 1'b1))) begin
        hBarSel_4_loc_0_fu_268 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_4_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hdata_flag_0_reg_374 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_flag_0_reg_374 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_loc_0_fu_248 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata_loc_0_fu_248 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rampVal_2_flag_0_reg_386 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_flag_0_reg_386 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_loc_0_fu_240 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2_loc_0_fu_240 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rampVal_3_flag_0_reg_362 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_flag_0_reg_362 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_loc_0_fu_276 <= rampVal_1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_loc_1_out_o_ap_vld == 1'b1))) begin
        rampVal_3_loc_0_fu_276 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_loc_0_fu_272 <= zext_ln1212_fu_659_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_loc_1_out_o_ap_vld == 1'b1))) begin
        rampVal_loc_0_fu_272 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        xBar_V_loc_0_fu_264 <= xBar_V;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_lhs_out_o_ap_vld == 1'b1))) begin
        xBar_V_loc_0_fu_264 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_lhs_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_224 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd0))) begin
        y_fu_224 <= y_4_fu_769_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        zonePlateVAddr_loc_0_fu_260 <= zonePlateVAddr;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1))) begin
        zonePlateVAddr_loc_0_fu_260 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        zonePlateVDelta_loc_0_fu_256 <= zonePlateVDelta;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        zonePlateVDelta_loc_0_fu_256 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd0))) begin
        add_ln1488_reg_1121 <= add_ln1488_fu_792_p2;
        cmp12_i_reg_1116 <= cmp12_i_fu_775_p2;
        or_ln1592_1_reg_1131 <= or_ln1592_1_fu_823_p2;
        or_ln1592_2_reg_1136 <= or_ln1592_2_fu_830_p2;
        or_ln1592_reg_1126 <= or_ln1592_fu_810_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_hdata_flag_0_phi_fu_378_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd1))) begin
        hdata <= hdata_new_0_fu_252;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata_new_0_fu_252 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_0_0_0_0487_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_0_0_0_0488_lcssa495_fu_228 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_0_0_0_0487_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_1_0_0_0489_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_1_0_0_0490_lcssa498_fu_232 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_1_0_0_0489_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_2_0_0_0491_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_2_0_0_0492_lcssa501_fu_236 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_p_0_2_0_0_0491_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd1))) begin
        rampStart <= add_ln705_fu_842_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        rampStart_load_reg_1087 <= rampStart;
        select_ln260_reg_1093 <= select_ln260_fu_687_p3;
        shl_ln_reg_1098[15 : 8] <= shl_ln_fu_695_p3[15 : 8];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_3_flag_0_phi_fu_366_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd1))) begin
        rampVal_1 <= rampVal_3_new_0_fu_280;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_2_flag_0_phi_fu_390_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd1))) begin
        rampVal_2 <= rampVal_2_new_0_fu_244;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2_new_0_fu_244 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_new_1_out_ap_vld == 1'b1))) begin
        rampVal_3_new_0_fu_280 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_xBar_V_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        xBar_V <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_xBar_V;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_3_reg_1108 <= y_fu_224;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVAddr;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        zonePlateVDelta <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_zonePlateVDelta;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_bckgndYUV_write;
    end else begin
        bckgndYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_764_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Sel_fu_782_p4 = {{y_fu_224[7:6]}};

assign add_i_fu_609_p2 = (trunc_ln506_fu_585_p1 + 14'd7);

assign add_ln1488_fu_792_p2 = (rampStart + trunc_ln518_fu_760_p1);

assign add_ln705_fu_842_p2 = (motionSpeed + rampStart);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_378_p4 = hdata_flag_0_reg_374;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_390_p4 = rampVal_2_flag_0_reg_386;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_366_p4 = rampVal_3_flag_0_reg_362;

assign ap_ready = internal_ap_ready;

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_bckgndYUV_din;

assign cmp12_i_fu_775_p2 = ((y_fu_224 != 16'd0) ? 1'b1 : 1'b0);

assign cmp2_i322_fu_589_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign cmp6_i_fu_603_p2 = ((colorFormat == 8'd1) ? 1'b1 : 1'b0);

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_ap_start_reg;

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_barWidth = {{add_i_fu_609_p2[13:3]}};

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_barWidth_cast = {{add_i_fu_609_p2[13:3]}};

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_cmp57_i = ((colorFormat != 8'd1) ? 1'b1 : 1'b0);

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_cmp85_i = ((tmp_fu_631_p4 != 7'd0) ? 1'b1 : 1'b0);

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_conv2_i_i_i = ((cmp2_i322_fu_589_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_select_ln1162_5 = ((cmp6_i_fu_603_p2[0:0] == 1'b1) ? 2'd1 : 2'd2);

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_398_trunc_ln = height[13:0];

assign icmp_ln1592_1_fu_804_p2 = ((Sel_fu_782_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln1592_2_fu_817_p2 = ((Sel_fu_782_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1592_fu_798_p2 = ((Sel_fu_782_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln518_fu_764_p2 = ((y_fu_224 == height) ? 1'b1 : 1'b0);

assign or_ln1592_1_fu_823_p2 = (icmp_ln1592_2_fu_817_p2 | icmp_ln1592_1_fu_804_p2);

assign or_ln1592_2_fu_830_p2 = (icmp_ln1592_fu_798_p2 | icmp_ln1592_2_fu_817_p2);

assign or_ln1592_fu_810_p2 = (icmp_ln1592_fu_798_p2 | icmp_ln1592_1_fu_804_p2);

assign select_ln260_fu_687_p3 = ((cmp2_i322_fu_589_p2[0:0] == 1'b1) ? rampStart : 8'd128);

assign shl_ln_fu_695_p3 = {{rampStart}, {8'd0}};

assign start_out = real_start;

assign tmp_fu_631_p4 = {{colorFormat[7:1]}};

assign trunc_ln506_fu_585_p1 = width[13:0];

assign trunc_ln518_fu_760_p1 = y_fu_224[7:0];

assign y_4_fu_769_p2 = (y_fu_224 + 16'd1);

assign zext_ln1212_fu_659_p1 = rampVal;

always @ (posedge ap_clk) begin
    shl_ln_reg_1098[7:0] <= 8'b00000000;
end

endmodule //main_flow_v_tpg_0_2_tpgBackground
