// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module main_flow_v_tpg_0_2_tpgForeground_Pipeline_VITIS_LOOP_729_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bckgndYUV_dout,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        bckgndYUV_empty_n,
        bckgndYUV_read,
        ovrlayYUV_din,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        ovrlayYUV_full_n,
        ovrlayYUV_write,
        loopWidth,
        pixOut_val_V_9,
        pixOut_val_V,
        pixOut_val_V_7,
        and4_i,
        and26_i,
        tobool,
        and10_i,
        ovrlayId_load,
        boxSize_1,
        y,
        zext_ln1869,
        vMax,
        hMax,
        zext_ln1869_1,
        cmp101_i,
        boxColorG_1,
        crossHairX_1,
        icmp_ln1918,
        cmp11_i200,
        cmp13_i,
        select_ln1930_1,
        boxHCoord_loc_1_out_i,
        boxHCoord_loc_1_out_o,
        boxHCoord_loc_1_out_o_ap_vld,
        boxVCoord_loc_1_out_i,
        boxVCoord_loc_1_out_o,
        boxVCoord_loc_1_out_o_ap_vld,
        boxHCoord,
        boxHCoord_ap_vld,
        boxVCoord,
        boxVCoord_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] bckgndYUV_dout;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input   bckgndYUV_empty_n;
output   bckgndYUV_read;
output  [23:0] ovrlayYUV_din;
input  [4:0] ovrlayYUV_num_data_valid;
input  [4:0] ovrlayYUV_fifo_cap;
input   ovrlayYUV_full_n;
output   ovrlayYUV_write;
input  [15:0] loopWidth;
input  [7:0] pixOut_val_V_9;
input  [7:0] pixOut_val_V;
input  [7:0] pixOut_val_V_7;
input  [0:0] and4_i;
input  [0:0] and26_i;
input  [0:0] tobool;
input  [0:0] and10_i;
input  [7:0] ovrlayId_load;
input  [15:0] boxSize_1;
input  [15:0] y;
input  [7:0] zext_ln1869;
input  [15:0] vMax;
input  [15:0] hMax;
input  [8:0] zext_ln1869_1;
input  [0:0] cmp101_i;
input  [7:0] boxColorG_1;
input  [15:0] crossHairX_1;
input  [0:0] icmp_ln1918;
input  [0:0] cmp11_i200;
input  [0:0] cmp13_i;
input  [1:0] select_ln1930_1;
input  [15:0] boxHCoord_loc_1_out_i;
output  [15:0] boxHCoord_loc_1_out_o;
output   boxHCoord_loc_1_out_o_ap_vld;
input  [15:0] boxVCoord_loc_1_out_i;
output  [15:0] boxVCoord_loc_1_out_o;
output   boxVCoord_loc_1_out_o_ap_vld;
output  [15:0] boxHCoord;
output   boxHCoord_ap_vld;
output  [15:0] boxVCoord;
output   boxVCoord_ap_vld;

reg ap_idle;
reg bckgndYUV_read;
reg ovrlayYUV_write;
reg[15:0] boxHCoord_loc_1_out_o;
reg boxHCoord_loc_1_out_o_ap_vld;
reg[15:0] boxVCoord_loc_1_out_o;
reg boxVCoord_loc_1_out_o_ap_vld;
reg boxHCoord_ap_vld;
reg boxVCoord_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln729_reg_849;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln729_fu_389_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] vDir;
reg   [0:0] hDir;
wire   [1:0] whiYuv_1_address0;
reg    whiYuv_1_ce0;
wire   [7:0] whiYuv_1_q0;
reg    ovrlayYUV_blk_n;
wire    ap_block_pp0_stage0;
reg    bckgndYUV_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] ovrlayId_load_read_read_fu_208_p2;
reg   [15:0] x_1_reg_838;
wire   [0:0] trunc_ln729_fu_385_p1;
reg   [0:0] trunc_ln729_reg_844;
reg   [0:0] icmp_ln729_reg_849_pp0_iter1_reg;
wire   [0:0] icmp_ln1839_fu_407_p2;
wire   [0:0] hDir_load_load_fu_413_p1;
wire   [0:0] icmp_ln1844_fu_421_p2;
wire   [0:0] icmp_ln1849_fu_433_p2;
wire   [0:0] vDir_load_load_fu_445_p1;
wire   [0:0] icmp_ln1856_fu_453_p2;
wire   [0:0] icmp_ln1861_fu_465_p2;
wire   [0:0] and_ln1918_fu_555_p2;
reg   [0:0] and_ln1918_reg_881;
wire   [0:0] or_ln1918_fu_561_p2;
reg   [0:0] or_ln1918_reg_888;
wire   [7:0] pixIn_val_V_fu_591_p1;
reg   [7:0] pixIn_val_V_reg_897;
wire   [7:0] pixIn_val_V_5_fu_595_p4;
reg   [7:0] pixIn_val_V_5_reg_903;
wire   [7:0] pixIn_val_V_6_fu_605_p4;
reg   [7:0] pixIn_val_V_6_reg_909;
wire   [0:0] and_ln1897_fu_677_p2;
reg   [0:0] and_ln1897_reg_915;
wire   [7:0] pixOut_val_V_8_fu_687_p3;
wire   [7:0] select_ln1918_fu_693_p3;
wire   [7:0] select_ln1918_1_fu_699_p3;
wire   [7:0] select_ln1918_2_fu_706_p3;
reg   [0:0] ap_phi_mux_empty_61_phi_fu_291_p8;
wire   [0:0] ap_phi_reg_pp0_iter0_empty_61_reg_288;
reg   [0:0] ap_phi_mux_empty_60_phi_fu_308_p8;
wire   [0:0] ap_phi_reg_pp0_iter0_empty_60_reg_305;
reg   [7:0] ap_phi_mux_pix_val_V_14_phi_fu_325_p10;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_14_reg_322;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_14_reg_322;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_val_V_14_reg_322;
reg   [7:0] ap_phi_mux_pix_val_V_13_phi_fu_340_p10;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_13_reg_337;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_13_reg_337;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_val_V_13_reg_337;
reg   [7:0] ap_phi_mux_pix_val_V_phi_fu_356_p10;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_reg_352;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_reg_352;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_val_V_reg_352;
wire   [63:0] zext_ln1930_fu_581_p1;
wire   [15:0] select_ln1866_fu_497_p3;
wire   [15:0] select_ln1870_fu_523_p3;
reg   [15:0] x_fu_126;
wire   [15:0] x_2_fu_395_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_x_1;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] or_ln1839_fu_401_p2;
wire   [15:0] zext_ln1869_1_cast_fu_369_p1;
wire   [15:0] zext_ln1869_cast_fu_373_p1;
wire   [15:0] sub_ln1869_fu_485_p2;
wire   [15:0] add_ln1867_fu_491_p2;
wire   [15:0] sub_ln1873_fu_511_p2;
wire   [15:0] add_ln1871_fu_517_p2;
wire   [0:0] icmp_ln1918_1_fu_549_p2;
wire   [0:0] or_ln1930_fu_567_p2;
wire   [1:0] select_ln1930_fu_573_p3;
wire   [0:0] icmp_ln1887_fu_633_p2;
wire   [15:0] boxBottom_fu_628_p2;
wire   [0:0] icmp_ln1892_fu_649_p2;
wire   [15:0] boxRight_fu_623_p2;
wire   [0:0] icmp_ln1887_1_fu_644_p2;
wire   [0:0] xor_ln1887_fu_638_p2;
wire   [0:0] icmp_ln1892_1_fu_660_p2;
wire   [0:0] xor_ln1892_fu_654_p2;
wire   [0:0] and_ln1897_2_fu_671_p2;
wire   [0:0] and_ln1897_1_fu_665_p2;
wire   [0:0] and_ln1902_fu_683_p2;
wire   [7:0] select_ln1948_fu_720_p3;
wire   [7:0] pixOut_val_V_13_fu_713_p3;
wire   [7:0] select_ln1946_fu_741_p3;
wire   [7:0] p_0_2_0_0_032128134_fu_727_p3;
wire   [7:0] empty_fu_748_p3;
wire   [7:0] pixOut_val_V_14_fu_734_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_265;
reg    ap_condition_318;
reg    ap_condition_321;
reg    ap_condition_253;
reg    ap_condition_312;
reg    ap_condition_347;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 vDir = 1'd0;
#0 hDir = 1'd0;
#0 ap_done_reg = 1'b0;
end

main_flow_v_tpg_0_2_tpgForeground_Pipeline_VITIS_LOOP_729_2_whiYuv_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_1_address0),
    .ce0(whiYuv_1_ce0),
    .q0(whiYuv_1_q0)
);

main_flow_v_tpg_0_2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_312)) begin
        if ((1'b1 == ap_condition_253)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_13_reg_337 <= pixOut_val_V_8_fu_687_p3;
        end else if ((1'b1 == ap_condition_321)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_13_reg_337 <= select_ln1918_1_fu_699_p3;
        end else if ((1'b1 == ap_condition_318)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_13_reg_337 <= {{bckgndYUV_dout[15:8]}};
        end else if ((1'b1 == ap_condition_265)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_13_reg_337 <= whiYuv_1_q0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_13_reg_337 <= ap_phi_reg_pp0_iter1_pix_val_V_13_reg_337;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_312)) begin
        if ((1'b1 == ap_condition_253)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_14_reg_322 <= pixOut_val_V_9;
        end else if ((1'b1 == ap_condition_321)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_14_reg_322 <= select_ln1918_fu_693_p3;
        end else if ((1'b1 == ap_condition_318)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_14_reg_322 <= {{bckgndYUV_dout[23:16]}};
        end else if ((1'b1 == ap_condition_265)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_14_reg_322 <= pixOut_val_V;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_14_reg_322 <= ap_phi_reg_pp0_iter1_pix_val_V_14_reg_322;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_312)) begin
        if ((1'b1 == ap_condition_253)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_reg_352 <= pixOut_val_V_7;
        end else if ((1'b1 == ap_condition_321)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_reg_352 <= select_ln1918_2_fu_706_p3;
        end else if ((1'b1 == ap_condition_318)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_reg_352 <= pixIn_val_V_fu_591_p1;
        end else if ((1'b1 == ap_condition_265)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_reg_352 <= 8'd240;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_val_V_reg_352 <= ap_phi_reg_pp0_iter1_pix_val_V_reg_352;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_347)) begin
        if (((icmp_ln1849_fu_433_p2 == 1'd1) & (hDir_load_load_fu_413_p1 == 1'd1))) begin
            hDir <= 1'd0;
        end else if (((icmp_ln1844_fu_421_p2 == 1'd1) & (hDir_load_load_fu_413_p1 == 1'd0))) begin
            hDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_347)) begin
        if (((icmp_ln1861_fu_465_p2 == 1'd1) & (vDir_load_load_fu_445_p1 == 1'd1))) begin
            vDir <= 1'd0;
        end else if (((icmp_ln1856_fu_453_p2 == 1'd1) & (vDir_load_load_fu_445_p1 == 1'd0))) begin
            vDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln729_fu_389_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_126 <= x_2_fu_395_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_126 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln729_reg_849 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        and_ln1897_reg_915 <= and_ln1897_fu_677_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln729_fu_389_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ovrlayId_load_read_read_fu_208_p2 == 8'd2))) begin
        and_ln1918_reg_881 <= and_ln1918_fu_555_p2;
        or_ln1918_reg_888 <= or_ln1918_fu_561_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln729_reg_849 <= icmp_ln729_fu_389_p2;
        icmp_ln729_reg_849_pp0_iter1_reg <= icmp_ln729_reg_849;
        trunc_ln729_reg_844 <= trunc_ln729_fu_385_p1;
        x_1_reg_838 <= ap_sig_allocacmp_x_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_13_reg_337 <= ap_phi_reg_pp0_iter0_pix_val_V_13_reg_337;
        ap_phi_reg_pp0_iter1_pix_val_V_14_reg_322 <= ap_phi_reg_pp0_iter0_pix_val_V_14_reg_322;
        ap_phi_reg_pp0_iter1_pix_val_V_reg_352 <= ap_phi_reg_pp0_iter0_pix_val_V_reg_352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln729_reg_849 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pixIn_val_V_5_reg_903 <= {{bckgndYUV_dout[15:8]}};
        pixIn_val_V_6_reg_909 <= {{bckgndYUV_dout[23:16]}};
        pixIn_val_V_reg_897 <= pixIn_val_V_fu_591_p1;
    end
end

always @ (*) begin
    if (((icmp_ln729_fu_389_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln729_fu_389_p2 == 1'd0) & (icmp_ln1856_fu_453_p2 == 1'd0) & (vDir_load_load_fu_445_p1 == 1'd0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1)) | ((icmp_ln729_fu_389_p2 == 1'd0) & (icmp_ln1861_fu_465_p2 == 1'd1) & (vDir_load_load_fu_445_p1 == 1'd1) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1)))) begin
        ap_phi_mux_empty_60_phi_fu_308_p8 = 1'd0;
    end else if ((((icmp_ln729_fu_389_p2 == 1'd0) & (icmp_ln1861_fu_465_p2 == 1'd0) & (vDir_load_load_fu_445_p1 == 1'd1) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1)) | ((icmp_ln729_fu_389_p2 == 1'd0) & (icmp_ln1856_fu_453_p2 == 1'd1) & (vDir_load_load_fu_445_p1 == 1'd0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1)))) begin
        ap_phi_mux_empty_60_phi_fu_308_p8 = 1'd1;
    end else begin
        ap_phi_mux_empty_60_phi_fu_308_p8 = ap_phi_reg_pp0_iter0_empty_60_reg_305;
    end
end

always @ (*) begin
    if ((((icmp_ln729_fu_389_p2 == 1'd0) & (icmp_ln1844_fu_421_p2 == 1'd0) & (hDir_load_load_fu_413_p1 == 1'd0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1)) | ((icmp_ln729_fu_389_p2 == 1'd0) & (icmp_ln1849_fu_433_p2 == 1'd1) & (hDir_load_load_fu_413_p1 == 1'd1) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1)))) begin
        ap_phi_mux_empty_61_phi_fu_291_p8 = 1'd0;
    end else if ((((icmp_ln729_fu_389_p2 == 1'd0) & (icmp_ln1849_fu_433_p2 == 1'd0) & (hDir_load_load_fu_413_p1 == 1'd1) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1)) | ((icmp_ln729_fu_389_p2 == 1'd0) & (icmp_ln1844_fu_421_p2 == 1'd1) & (hDir_load_load_fu_413_p1 == 1'd0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1)))) begin
        ap_phi_mux_empty_61_phi_fu_291_p8 = 1'd1;
    end else begin
        ap_phi_mux_empty_61_phi_fu_291_p8 = ap_phi_reg_pp0_iter0_empty_61_reg_288;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln1897_reg_915) & (icmp_ln729_reg_849_pp0_iter1_reg == 1'd0) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        ap_phi_mux_pix_val_V_13_phi_fu_340_p10 = pixIn_val_V_5_reg_903;
    end else begin
        ap_phi_mux_pix_val_V_13_phi_fu_340_p10 = ap_phi_reg_pp0_iter2_pix_val_V_13_reg_337;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln1897_reg_915) & (icmp_ln729_reg_849_pp0_iter1_reg == 1'd0) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        ap_phi_mux_pix_val_V_14_phi_fu_325_p10 = pixIn_val_V_6_reg_909;
    end else begin
        ap_phi_mux_pix_val_V_14_phi_fu_325_p10 = ap_phi_reg_pp0_iter2_pix_val_V_14_reg_322;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln1897_reg_915) & (icmp_ln729_reg_849_pp0_iter1_reg == 1'd0) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        ap_phi_mux_pix_val_V_phi_fu_356_p10 = pixIn_val_V_reg_897;
    end else begin
        ap_phi_mux_pix_val_V_phi_fu_356_p10 = ap_phi_reg_pp0_iter2_pix_val_V_reg_352;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_1 = 16'd0;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln729_reg_849 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bckgndYUV_blk_n = bckgndYUV_empty_n;
    end else begin
        bckgndYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln729_reg_849 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bckgndYUV_read = 1'b1;
    end else begin
        bckgndYUV_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln729_fu_389_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        boxHCoord_ap_vld = 1'b1;
    end else begin
        boxHCoord_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln729_fu_389_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        boxHCoord_loc_1_out_o = select_ln1866_fu_497_p3;
    end else begin
        boxHCoord_loc_1_out_o = boxHCoord_loc_1_out_i;
    end
end

always @ (*) begin
    if (((icmp_ln729_fu_389_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        boxHCoord_loc_1_out_o_ap_vld = 1'b1;
    end else begin
        boxHCoord_loc_1_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln729_fu_389_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        boxVCoord_ap_vld = 1'b1;
    end else begin
        boxVCoord_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln729_fu_389_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        boxVCoord_loc_1_out_o = select_ln1870_fu_523_p3;
    end else begin
        boxVCoord_loc_1_out_o = boxVCoord_loc_1_out_i;
    end
end

always @ (*) begin
    if (((icmp_ln729_fu_389_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1))) begin
        boxVCoord_loc_1_out_o_ap_vld = 1'b1;
    end else begin
        boxVCoord_loc_1_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ovrlayYUV_blk_n = ovrlayYUV_full_n;
    end else begin
        ovrlayYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ovrlayYUV_write = 1'b1;
    end else begin
        ovrlayYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        whiYuv_1_ce0 = 1'b1;
    end else begin
        whiYuv_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1867_fu_491_p2 = (boxHCoord_loc_1_out_i + zext_ln1869_cast_fu_373_p1);

assign add_ln1871_fu_517_p2 = (boxVCoord_loc_1_out_i + zext_ln1869_cast_fu_373_p1);

assign and_ln1897_1_fu_665_p2 = (xor_ln1887_fu_638_p2 & icmp_ln1887_1_fu_644_p2);

assign and_ln1897_2_fu_671_p2 = (xor_ln1892_fu_654_p2 & icmp_ln1892_1_fu_660_p2);

assign and_ln1897_fu_677_p2 = (and_ln1897_2_fu_671_p2 & and_ln1897_1_fu_665_p2);

assign and_ln1902_fu_683_p2 = (trunc_ln729_reg_844 & cmp101_i);

assign and_ln1918_fu_555_p2 = (icmp_ln1918_1_fu_549_p2 & icmp_ln1918);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ovrlayYUV_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((icmp_ln729_reg_849 == 1'd0) & (bckgndYUV_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ovrlayYUV_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((icmp_ln729_reg_849 == 1'd0) & (bckgndYUV_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ovrlayYUV_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((icmp_ln729_reg_849 == 1'd0) & (bckgndYUV_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln729_reg_849 == 1'd0) & (bckgndYUV_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (ovrlayYUV_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_253 = ((1'd1 == and_ln1897_fu_677_p2) & (icmp_ln729_reg_849 == 1'd0) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1));
end

always @ (*) begin
    ap_condition_265 = ((icmp_ln729_reg_849 == 1'd0) & (or_ln1918_reg_888 == 1'd0) & (ovrlayId_load_read_read_fu_208_p2 == 8'd2));
end

always @ (*) begin
    ap_condition_312 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_318 = (~(ovrlayId_load_read_read_fu_208_p2 == 8'd2) & ~(ovrlayId_load_read_read_fu_208_p2 == 8'd1) & (icmp_ln729_reg_849 == 1'd0));
end

always @ (*) begin
    ap_condition_321 = ((icmp_ln729_reg_849 == 1'd0) & (or_ln1918_reg_888 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd2));
end

always @ (*) begin
    ap_condition_347 = ((icmp_ln729_fu_389_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1839_fu_407_p2 == 1'd1) & (ovrlayId_load_read_read_fu_208_p2 == 8'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_empty_60_reg_305 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_61_reg_288 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_13_reg_337 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_14_reg_322 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_reg_352 = 'bx;

assign boxBottom_fu_628_p2 = (boxSize_1 + boxVCoord_loc_1_out_i);

assign boxHCoord = ((ap_phi_mux_empty_61_phi_fu_291_p8[0:0] == 1'b1) ? sub_ln1869_fu_485_p2 : add_ln1867_fu_491_p2);

assign boxRight_fu_623_p2 = (boxSize_1 + boxHCoord_loc_1_out_i);

assign boxVCoord = ((ap_phi_mux_empty_60_phi_fu_308_p8[0:0] == 1'b1) ? sub_ln1873_fu_511_p2 : add_ln1871_fu_517_p2);

assign empty_fu_748_p3 = ((tobool[0:0] == 1'b1) ? ap_phi_mux_pix_val_V_13_phi_fu_340_p10 : select_ln1946_fu_741_p3);

assign hDir_load_load_fu_413_p1 = hDir;

assign icmp_ln1839_fu_407_p2 = ((or_ln1839_fu_401_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1844_fu_421_p2 = ((boxHCoord_loc_1_out_i > hMax) ? 1'b1 : 1'b0);

assign icmp_ln1849_fu_433_p2 = ((boxHCoord_loc_1_out_i < zext_ln1869_1_cast_fu_369_p1) ? 1'b1 : 1'b0);

assign icmp_ln1856_fu_453_p2 = ((boxVCoord_loc_1_out_i > vMax) ? 1'b1 : 1'b0);

assign icmp_ln1861_fu_465_p2 = ((boxVCoord_loc_1_out_i < zext_ln1869_1_cast_fu_369_p1) ? 1'b1 : 1'b0);

assign icmp_ln1887_1_fu_644_p2 = ((y < boxBottom_fu_628_p2) ? 1'b1 : 1'b0);

assign icmp_ln1887_fu_633_p2 = ((y < boxVCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1892_1_fu_660_p2 = ((x_1_reg_838 < boxRight_fu_623_p2) ? 1'b1 : 1'b0);

assign icmp_ln1892_fu_649_p2 = ((x_1_reg_838 < boxHCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1918_1_fu_549_p2 = ((ap_sig_allocacmp_x_1 != crossHairX_1) ? 1'b1 : 1'b0);

assign icmp_ln729_fu_389_p2 = ((ap_sig_allocacmp_x_1 == loopWidth) ? 1'b1 : 1'b0);

assign or_ln1839_fu_401_p2 = (y | ap_sig_allocacmp_x_1);

assign or_ln1918_fu_561_p2 = (cmp11_i200 | and_ln1918_fu_555_p2);

assign or_ln1930_fu_567_p2 = (trunc_ln729_fu_385_p1 | cmp13_i);

assign ovrlayId_load_read_read_fu_208_p2 = ovrlayId_load;

assign ovrlayYUV_din = {{{p_0_2_0_0_032128134_fu_727_p3}, {empty_fu_748_p3}}, {pixOut_val_V_14_fu_734_p3}};

assign p_0_2_0_0_032128134_fu_727_p3 = ((tobool[0:0] == 1'b1) ? ap_phi_mux_pix_val_V_14_phi_fu_325_p10 : select_ln1948_fu_720_p3);

assign pixIn_val_V_5_fu_595_p4 = {{bckgndYUV_dout[15:8]}};

assign pixIn_val_V_6_fu_605_p4 = {{bckgndYUV_dout[23:16]}};

assign pixIn_val_V_fu_591_p1 = bckgndYUV_dout[7:0];

assign pixOut_val_V_13_fu_713_p3 = ((and4_i[0:0] == 1'b1) ? 8'd0 : ap_phi_mux_pix_val_V_phi_fu_356_p10);

assign pixOut_val_V_14_fu_734_p3 = ((tobool[0:0] == 1'b1) ? ap_phi_mux_pix_val_V_phi_fu_356_p10 : pixOut_val_V_13_fu_713_p3);

assign pixOut_val_V_8_fu_687_p3 = ((and_ln1902_fu_683_p2[0:0] == 1'b1) ? pixOut_val_V_9 : boxColorG_1);

assign select_ln1866_fu_497_p3 = ((ap_phi_mux_empty_61_phi_fu_291_p8[0:0] == 1'b1) ? sub_ln1869_fu_485_p2 : add_ln1867_fu_491_p2);

assign select_ln1870_fu_523_p3 = ((ap_phi_mux_empty_60_phi_fu_308_p8[0:0] == 1'b1) ? sub_ln1873_fu_511_p2 : add_ln1871_fu_517_p2);

assign select_ln1918_1_fu_699_p3 = ((and_ln1918_reg_881[0:0] == 1'b1) ? pixIn_val_V_5_fu_595_p4 : 8'd240);

assign select_ln1918_2_fu_706_p3 = ((and_ln1918_reg_881[0:0] == 1'b1) ? pixIn_val_V_fu_591_p1 : 8'd240);

assign select_ln1918_fu_693_p3 = ((and_ln1918_reg_881[0:0] == 1'b1) ? pixIn_val_V_6_fu_605_p4 : pixOut_val_V);

assign select_ln1930_fu_573_p3 = ((or_ln1930_fu_567_p2[0:0] == 1'b1) ? select_ln1930_1 : 2'd1);

assign select_ln1946_fu_741_p3 = ((and10_i[0:0] == 1'b1) ? 8'd0 : ap_phi_mux_pix_val_V_13_phi_fu_340_p10);

assign select_ln1948_fu_720_p3 = ((and26_i[0:0] == 1'b1) ? 8'd0 : ap_phi_mux_pix_val_V_14_phi_fu_325_p10);

assign sub_ln1869_fu_485_p2 = (boxHCoord_loc_1_out_i - zext_ln1869_cast_fu_373_p1);

assign sub_ln1873_fu_511_p2 = (boxVCoord_loc_1_out_i - zext_ln1869_cast_fu_373_p1);

assign trunc_ln729_fu_385_p1 = ap_sig_allocacmp_x_1[0:0];

assign vDir_load_load_fu_445_p1 = vDir;

assign whiYuv_1_address0 = zext_ln1930_fu_581_p1;

assign x_2_fu_395_p2 = (ap_sig_allocacmp_x_1 + 16'd1);

assign xor_ln1887_fu_638_p2 = (icmp_ln1887_fu_633_p2 ^ 1'd1);

assign xor_ln1892_fu_654_p2 = (icmp_ln1892_fu_649_p2 ^ 1'd1);

assign zext_ln1869_1_cast_fu_369_p1 = zext_ln1869_1;

assign zext_ln1869_cast_fu_373_p1 = zext_ln1869;

assign zext_ln1930_fu_581_p1 = select_ln1930_fu_573_p3;

endmodule //main_flow_v_tpg_0_2_tpgForeground_Pipeline_VITIS_LOOP_729_2
